// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnicaP1.DataAccess;

#nullable disable

namespace PruebaTecnicaP1.DataAccess.Migrations
{
    [DbContext(typeof(ProyectoContext))]
    partial class ProyectoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("PruebaTecnicaP1.Models.Entities.Covid", b =>
                {
                    b.Property<long>("CovidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveCases")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RegionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalCases")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.HasKey("CovidId");

                    b.HasIndex("RegionId");

                    b.ToTable("Covids", (string)null);
                });

            modelBuilder.Entity("PruebaTecnicaP1.Models.Entities.Region", b =>
                {
                    b.Property<long>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegionId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("PruebaTecnicaP1.Models.Entities.Covid", b =>
                {
                    b.HasOne("PruebaTecnicaP1.Models.Entities.Region", "Region")
                        .WithMany("Covids")
                        .HasForeignKey("RegionId")
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PruebaTecnicaP1.Models.Entities.Region", b =>
                {
                    b.Navigation("Covids");
                });
#pragma warning restore 612, 618
        }
    }
}
